// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HollywoodMessage } from "./HollywoodMessage";
import type { HollywoodMessageAttention } from "./HollywoodMessageAttention";

export type HollywoodMessageNotification = { threadId: string, message: HollywoodMessage, attention: HollywoodMessageAttention, mentioned: boolean, selfAuthored: boolean, };
