// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HollywoodAttentionSettings } from "./HollywoodAttentionSettings";
import type { HollywoodSessionStatus } from "./HollywoodSessionStatus";

export type HollywoodSessionState = { attached: boolean, url: string, primaryRoom: string, observedRooms: Array<string>, wakeRooms: Array<string>, attention: HollywoodAttentionSettings, identities: Array<string>, sessionKind: string | null, resumedFrom: string | null, status: HollywoodSessionStatus, diagnostics: HollywoodSessionDiagnostics | null, };
