// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HollywoodMessageKind } from "./HollywoodMessageKind";
import type { HollywoodResponsePolicy } from "./HollywoodResponsePolicy";

export type HollywoodMessage = { id: bigint, room: string, senderId: string | null, recipientId: string | null, messageKind: HollywoodMessageKind, responsePolicy: HollywoodResponsePolicy, body: string, createdAt: string, mentions: Array<string>, };
