// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadOwnershipPathClaim } from "./ThreadOwnershipPathClaim";
import type { ThreadOwnershipPathSpec } from "./ThreadOwnershipPathSpec";

export type ThreadOwnershipPathClaimConflict = { requested: ThreadOwnershipPathSpec, blockingClaim: ThreadOwnershipPathClaim, };
