// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadOwnershipPathKind } from "./ThreadOwnershipPathKind";

export type ThreadOwnershipPathClaim = { id: string, ownerThreadId: string, kind: ThreadOwnershipPathKind, path: string, claimedAt: bigint, updatedAt: bigint, leaseExpiresAt: bigint, };
